title = "Denver Noell"
baseURL = "https://portfolio.denvernoell.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Visalia, CA"
email = "Denver@denvernoell.com"
favicon = "/favicon.ico"
firstName = "Denver"
lastName = "Noell"
phone = "1-559-731-2221"
profileImage = "img/profile-pic_round_stripes.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/denver-noell-eit-02840016b/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/denvernoell/"
name = "GitHub"

[[params.handles]]
link = "https://denvernoell.com/"
name = "Hashnode"
icon = "pencil-alt"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true